author = 'sujit shakya'
k = 3
n = 10
no_of_users = 943
no_of_items = 1682
total_ratings = 100000
trainingData = "data/dataset/u.data"
itemData = "data/dataset/u.item"
CLUSTER_NAME = "data/dataset/u.cluster"